#pragma config(Sensor, in1,    clawRightPot,   sensorPotentiometer)
#pragma config(Sensor, in2,    clawLeftPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl2,  driveRightQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  driveLeftQuad,  sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  liftQuad,       sensorQuadEncoder)
#pragma config(Motor,  port1,           liftRightBottomOutside, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRight,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftLeftTopOutside, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeftMiddle, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightMiddle, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           clawLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           liftRightTopOutside, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          liftLeftBottomOutside, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//Main competition background code...do not modify!


task main{
	while(true){
		if(vexRT[Btn7D]==1){
			motor[liftRightTopOutside] = 127;
		}
		else{
			motor[liftLeftMiddle]=0;
			motor[liftLeftBottomOutside]=0;
			motor[liftLeftTopOutside]=0;
			motor[liftRightMiddle]=0;
			motor[liftRightBottomOutside]=0;
			motor[liftRightTopOutside]=0;
		}
	}
}
