#pragma config(Sensor, in1,    clawRightPot,   sensorPotentiometer)
#pragma config(Sensor, in2,    clawLeftPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveRightQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveLeftQuad,  sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  liftQuad,       sensorQuadEncoder)
#pragma config(Motor,  port1,           liftLeftMid,   tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           clawLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftRightMid,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           driveRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftRightTop,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftLeftTop,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftRightOut,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           clawRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          liftLeftOut,   tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//Main competition background code...do not modify!


task main{
	while(true){
		if(vexRT[Btn7D]==1){
			motor[liftRightTop] = 127;
		}
		else{
			motor[liftLeftMid]=0;
			motor[liftLeftOut]=0;
			motor[liftLeftTop]=0;
			motor[liftRightMid]=0;
			motor[liftRightOut]=0;
			motor[liftRightTop]=0;
		}
	}
}
