#pragma config(Sensor, in1,    clawRightPot,   sensorPotentiometer)
#pragma config(Sensor, in2,    clawLeftPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl2,  driveRightQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  driveLeftQuad,  sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  liftQuad,       sensorQuadEncoder)
#pragma config(Motor,  port1,           liftRightBottomOutside, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRight,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftLeftTopOutside, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftLeftMiddle, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftRightMiddle, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           clawLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           liftRightTopOutside, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          liftLeftBottomOutside, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Drive Functions.c"
#include "Lift Functions.c"
#include "Sensor Functions.c"
#include "Claw Left Functions.c"
#include "Claw Right Functions.c"
#include "Throw Functions.c"
#include "LCD Functions.c"
#include "Autonomous Functions.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{



	bLCDBacklight = true; // Turn on LCD Backlight

	// check if the robot is disabled or enabled
	//if (nVexRCReceiveState & vrDisabled) {
	//	// Disabled
	//}
	//else {
	//	// Enabled
	//	return; // skip LCD selection
	//}

	// Display the battery level

	// Code Chooser
	while(nLCDButtons != centerButton) {
		switch(count){

		case 0:
			displayLCDCenteredString(0, "<No Autonomous>");
			WaitForPressAndRelease(14); // go forward to 4 if left is pressed
			break;

		case 1:
			displayLCDCenteredString(0, "<Red Left Main>");
			WaitForPressAndRelease();
			break;

		case 2:
			displayLCDCenteredString(0, "<Red Left Alt>");
			WaitForPressAndRelease();
			break;

		case 3:
			displayLCDCenteredString(0, "<Red Left E>");
			WaitForPressAndRelease();
			break;

		case 4:
			displayLCDCenteredString(0, "<Red Right Main>");
			WaitForPressAndRelease();
			break;

		case 5:
			displayLCDCenteredString(0, "<Red Right Alt>");
			WaitForPressAndRelease();
			break;

		case 6:
			displayLCDCenteredString(0, "<Red Right E>");
			WaitForPressAndRelease();
			break;

		case 7:
			displayLCDCenteredString(0, "<Blue Left Main>");
			WaitForPressAndRelease();
			break;

		case 8:
			displayLCDCenteredString(0, "<Blue Left Alt>");
			WaitForPressAndRelease();
			break;
		case 9:
			displayLCDCenteredString(0, "<Blue Left E>");
			WaitForPressAndRelease();
			break;

		case 10:
			displayLCDCenteredString(0, "<Blue Right Main>");
			WaitForPressAndRelease();
			break;

		case 11:
			displayLCDCenteredString(0, "<Blue Right Alt>");
			WaitForPressAndRelease();
			break;

		case 12:
			displayLCDCenteredString(0, "<Blue Right E>");
			WaitForPressAndRelease();
			break;

		case 13:
			displayLCDCenteredString(0, "<Prog Skills>");
			WaitForPressAndRelease(); // go back to zero if right is pressed
			break;

		case 14:
			displayLCDCenteredString(0, "<Test>");
			WaitForPressAndRelease(0); // go back to zero if right is pressed
			break;
		}

	}
	displayLCDCenteredString(0, "Calibrating gyro");
	displayLCDCenteredString(1, "DO NOT MOVE");
	wait1Msec(2000);
	SensorType[in8] = sensorNone;
	wait1Msec(2000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in8] = sensorGyro;
	wait1Msec(2000);
	SensorScale[in8] = 139;

	clearLCDLine(0);
	clearLCDLine(1);

	SensorValue(liftQuad) = 0;
	SensorValue(driveLeftQuad) = 0;
	SensorValue(driveRightQuad) = 0;


	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task combinedControl(){ //drive, lift, clawinput
	while(true){
		//driveControl
		motor[port4] = vexRT[Ch3]+ vexRT[Ch1];
		motor[port2] = vexRT[Ch3] -vexRT[Ch1];

		//liftControl


		if(vexRT[Btn5U] == 1 && (SensorValue(liftQuad)<780|| vexRT[Btn8UXmtr2])){
			setLift(127);
			setPosition_lift = SensorValue(liftQuad)+30;
		}
		else if (vexRT[Btn5D]==1&& SensorValue(liftQuad)>-1){
			setLift(-127);
			setPosition_lift = SensorValue(liftQuad)-30;
		}
		else{
			currentPositon_lift = SensorValue(liftQuad);

			error_lift = setPosition_lift - currentPositon_lift;
			int speed = kP_lift * error_lift;
			setLift(speed);
		}

		//Claw Contol

		if(vexRT[Btn6U] == 1){
			motor[clawLeft] = 127;
			motor[clawRight] = 127;
			currentPosition_CL = SensorValue[clawLeftPot] + 1;
			currentPosition_CR = SensorValue[clawRightPot] + 1;
		}
		else if(vexRT[Btn6D] == 1){
			motor[clawLeft] = -127;
			motor[clawRight] = -127;
			currentPosition_CL = SensorValue[clawLeftPot] - 1;
			currentPosition_CR = SensorValue[clawRightPot] - 1;
		}
		else if(vexRT[Btn8RXmtr2] == 1 || SensorValue[liftQuad] > 500){
			currentPosition_CL = clawLeftPositionOpen;
			currentPosition_CR = clawRightPositionOpen;
			clawLeftControlPID(currentPosition_CL);
			clawRightControlPID(currentPosition_CR);
		}
		else{
			clawLeftControlPID(currentPosition_CL);
			clawRightControlPID(currentPosition_CR);
		}
		wait1Msec(10);
	}
}


task liftControlAuton(){
	while(true){
		while(runPID_lift){
			currentPositon_lift = SensorValue(liftQuad);

			error_lift = setPosition_lift - currentPositon_lift;
			int speed = kP_lift * error_lift;
			setLift(speed);
		}
	}
	wait1Msec(5);
}


task liftThrow(){
while(true){

	liftPosition = SensorValue(liftQuad);

	//if((vexRT[Btn8DXmtr2]==1) && (liftPosition>lastLiftPosition) && liftPosition>throwThresholdClose){
	//	clawLeftSetPosition(clawLeftPositionOpen);
	//	clawRightSetPosition(clawRightPositionOpen);
	//}
	if((liftPosition>lastLiftPosition) && liftPosition>throwThresholdFar){
		clawLeftSetPosition(clawLeftPositionOpen);
		clawRightSetPosition(clawRightPositionOpen);
	}


	lastLiftPosition = SensorValue(liftQuad);
	wait1Msec(10);
}
}

task liftThrowAuton(){
while(true){

	liftPosition = SensorValue(liftQuad);

	//if((vexRT[Btn8DXmtr2]==1) && (liftPosition>lastLiftPosition) && liftPosition>throwThresholdClose){
	//	clawLeftSetPosition(clawLeftPositionOpen);
	//	clawRightSetPosition(clawRightPositionOpen);
	//}
	if((liftPosition>lastLiftPosition) && liftPosition>throwThresholdFar && runThrow){
		clawLeftSetPosition(clawLeftPositionOpen);
		clawRightSetPosition(clawRightPositionOpen);
	}


	lastLiftPosition = SensorValue(liftQuad);
	wait1Msec(10);
}
}




//writeDebugStream("%f", currentPosition_CL);
//writeDebugStream(",");
//writeDebugStream("%f", setPosition_CL);
//writeDebugStream(",");
//writeDebugStream("%f", speed_CL);
//writeDebugStream(",");
//writeDebugStream("%f", proportional_effect);
//writeDebugStream(",");
//writeDebugStream("%f", derivative_effect);
//writeDebugStreamLine("%f", time1[T1]);


//			wait1Msec(10);
//		}

//	}

//}



task autonomous()
{

startTask(liftControlAuton);
//startTask(clawLeftControl);
//startTask(clawRightControl);
startTask(liftThrowAuton);
wait1Msec(1);

bLCDBacklight = true; // Turn on LCD Backlight
displayLCDCenteredString(0, "Autonomous");
switch(count){
case 0:
	// No Autonomous
	displayLCDCenteredString(1, "No Autonomous");
	break;
case 1:
	displayLCDCenteredString(1, "Red Left Main");
	auton_red_left_main();
	break;
case 2:
	displayLCDCenteredString(1, "Red Left Alt");
	auton_red_left_alt();
	break;
case 3:
	displayLCDCenteredString(1, "Red Left E");
	auton_red_left_E();
	break;
case 4:
	displayLCDCenteredString(1, "Red Right Main");
	auton_red_right_main();
	break;
case 5:
	displayLCDCenteredString(1, "Red Right Alt");
	auton_red_right_alt();
	break;
case 6:
	displayLCDCenteredString(1, "Red Right E");
	auton_red_right_E();
	break;
case 7:
	displayLCDCenteredString(1, "Blue Left Main");
	auton_blue_left_main();
	break;
case 8:
	// test
	displayLCDCenteredString(1, "Blue Left Alt");
	auton_blue_left_alt();
	break;
case 9:
	// test
	displayLCDCenteredString(1, "Blue Left E");
	auton_blue_left_E();
	break;
case 10:
	// test
	displayLCDCenteredString(1, "Blue Right Main");
	auton_blue_right_main();
	break;
case 11:
	// test
	displayLCDCenteredString(1, "Blue Right Alt");
	auton_blue_right_alt();
	break;
case 12:
	// test
	displayLCDCenteredString(1, "Blue Right E");
	auton_blue_right_E();
	break;
case 13:
	// test
	displayLCDCenteredString(1, "Prog Skills");
	auton_programmingskills();
	break;
case 14:
	// test
	displayLCDCenteredString(1, "Test");
	auton_test();
	break;
}
}

task usercontrol()
{
datalogClear();
wait1Msec(1);
//startTask(clawLeftControl);
//startTask(clawRightControl);
startTask(combinedControl);
//startTask(liftThrow);
//startTask(grapher);

}
