#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in5,    clawRightPot,   sensorPotentiometer)
#pragma config(Sensor, in6,    clawLeftPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveRightQuad, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveLeftQuad,  sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  liftQuad,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           liftLeftMid,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           clawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           liftRightMid,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftRightTop,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeftTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftRightOut,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftLeftOut,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          clawRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Drive Functions.c"
#include "Lift Functions.c"
#include "Sensor Functions.c"
#include "Claw Functions.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	nMotorEncoder[liftLeftOut] = 0;
	resetDriveSensors();

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task driveControl(){

	while(true){
		//setDriveRight(vexRT[Ch3] - vexRT[Ch1]);
		//setDriveLeft(vexRT[Ch3] + vexRT[Ch1]);
		motor[port3] = vexRT[Ch3]+ vexRT[Ch1];
		motor[port5] = vexRT[Ch3] -vexRT[Ch1];
		wait1Msec(5);

	}
}

task liftControl(){
	while(true){
		if(vexRT[Btn5U] == 1){
			setLift(127);
		}
		else if (vexRT[Btn5D]==1){
			setLift(-127);
		}
		else if(vexRT[Btn6U] == 1){
			setLiftPosition(liftPositionTop);
		}
		else if (vexRT[Btn6D]==1){
			setLiftPosition(liftPositionBottom);
		}
		else if(vexRT[Btn8U]==1){
			setLiftPosition(liftPositionMid);
		}
		else{
			setLift(10);
		}
		wait1Msec(5);

	}
}
task clawLeftControlPID(){
	clawLeftSetPosition(2000);
		while(true){
		currentPosition = SensorValue(clawLeftPot);
		error = setPosition - currentPosition;
		integral += error;

		if(lastCurrentPosition != currentPosition){
			integral = 0;
		}
		derivative = currentPosition-lastCurrentPosition;
		lastCurrentPosition = currentPosition;


		if(integral> integralCap){
			integral = integralCap;
		}
		int speed = (kP * error) + (kI * integral) + (kD * derivative);
		if(speed>80){
			speed=80;
		}
		else if(speed < -80){
			speed = -80;
		}
		setClawLeft(speed);
		wait1Msec(10);

	}

}

task clawLeftControl(){
	//while(true){
	//if(vexRT[Btn6U] == 1){ // open
	//	setClawLeftPosition(1800);
	//}
	//else if(vexRT[Btn6D]==1){ //close
	//  setClawLeftPosition(2900);
	//}
	while(true){
		if(vexRT[Btn5UXmtr2]==1){
			motor[clawLeft] = 127;
		}
		else if(vexRT[Btn5DXmtr2]==1){
			motor[clawLeft] = -127;
		}
		else{
			motor[clawLeft] = 0;
		}

		if(vexRT[Btn6UXmtr2]==1){
			motor[clawRight] = 127;
		}
		else if(vexRT[Btn6DXmtr2]==1){
			motor[clawRight] = -127;
		}
		else{
			motor[clawRight] = 0;
		}

	}

	wait1Msec(5);
}


task clawRightControl(){
	//while(true){
	//	if(vexRT[Btn6U] == 1){ // open
	//		setClawRightPosition(1600);
	//	}
	//	else if(vexRT[Btn6D]==1){ //close
	//		setClawRightPosition(800);
	//	}

	//wait1Msec(5);
}


task usercontrol()
{
	startTask(driveControl);
	startTask(liftControl);
	//startTask(clawLeftControl);
	startTask(clawLeftControlPID);
	//	startTask(clawRightControl);

	while(true){

	}
	// User control code here, inside the loop
}
